version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ggebot_postgres
    restart: always
    environment:
      POSTGRES_USER: un1c4on
      POSTGRES_PASSWORD: un1c4on
      POSTGRES_DB: ggebot_db
    ports:
      - "5433:5432"
    volumes:
      - ggebot_pgdata:/var/lib/postgresql/data

volumes:
  ggebot_pgdata:
    name: ggebot_pgdata  # Named volume - veri kaybını önler
