version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: gge-bot-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: un1c4on
      POSTGRES_DB: ggebot_db
    ports:
      - "5433:5432" # Dışarıdan (ve botun çalıştığı sunucudan) erişim için 5433 portu
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
